### ISSUE TITLE
firehol start = autorestore

### ISSUE THREAD

**Issue by philwhineray** [ktsaou/firehol#43] opened 2015-01-03 10:45 UTC
I like the new `firehol restore` function. Would it be made even better by saving the config file or a checksum to the spool directory during the initial `start`? Then when a later `firehol start` is executed, if everything still matches we just run `restore`, that way everyone gets the functionality by default.

It would also mean we can check for dynamic rules such as rpc during the save, and create a file to disable the autorestore, so a user will always get an up-to-date firewall: fast if possible, slow if necessary.

**Comment by ktsaou** [comment] 2015-01-03 12:06
Happy New Year Phil,

Well, there are still cases where this will not work as expected:

1. There are a lot of folks that split large firewalls to multiple files which are included from `firehol.conf`. There is no way to find this out without pre-processing the configuration.

2. There are firewalls that detect ports at runtime. Even the stock nfs service does it this way. `firehol.conf` is not changed, but the firewall is different.

So, I thought it would be better for the admins to use `restore` only if they know what they are doing.  If we make `start` behave like `restore`, then the only way to re-process the firewall sould be to open `firehol.conf` in an editor and add a space or newline somewhere...

On the other hand, probably we could settle both issues by having a file like `/etc/firehol/defaults.conf` which will set just default values for firehol, in all modes of operation (firehol will always load this file on startup).
In this file we could have:

```sh
ENABLE_IPV4=1
ENABLE_IPV6=1
FIREHOL_CONFIG_FILES="/etc/firehol/firehol.conf /etc/firehol/anotherfile.conf"
DYNAMIC_FIREWALL=0 # 1 means 'restore' is disabled
```

This would settle both issues above and probably a few more.

Lets think about it...

**Comment by philwhineray** [comment] 2015-01-03 13:32
Happy New Year, to you too.

We can know when we have used a firehol dynamic rule such as nfs, so we can ensure automatic restore does not happed for such a setup.

I guess it is impossible to solve the rest automatically since we will not know a file was sourced or if the user builds rules dynamically in some way. So it is probably a bad idea to enable autorestore by default.

Taking your idea of a defaults file, it would be possible to make it clear to the administrator what they would be enabling:

````
RESTORE_ON_START_IF_UNCHANGED="/etc/firehol/firehol.conf /etc/firehol/another.conf /etc/extra-file"
````

Then `start` looks for a known checksum file e.g. `/var/spool/firehol/autorestore`. If it is found and the checksums match then `restore` is used, otherwise there is a normal `start`.

The file can be created in the spool directory after a successful start and provided the variable has been set.

The file is not created if the variable is not set or if we detect a dynamic rule (in which case we should probably emit a warning).

On reflection I guess the control variable could go in the normal `firehol.conf` as well, without problem.

**Comment by ktsaou** [comment] 2015-01-06 17:58
Phil, I just pushed a version that implements start = restore.
I didn't do a checksum on the files. I though the problem is more complex. May be PRIVATE_IPS or some other minor file may have changed. It would be impossible to remember all the files that could be changed.

So, I decided to find if there is a file in /etc/firehol and /etc/firehol/services that is newer than the saved firewall.

Also, I did a check for the command line options passed to firehol.conf by the admin. If anything changes, the firewall is started, not restored.

At the same time, I implemented the defaults.conf file. I moved all the options at the top of firehol, added documentation and code to generate the defaults file if it does not exist.

Check it and let me know if you find any issues.

**Comment by philwhineray** [comment] 2015-01-10 15:43
Costa, I have done some checks and it all seems to work well to me.  I will close this now, if I hit any problems I will document them separately.

I am especially liking the new defaults file as it happens, it works very nicely.

I am looking at some bridging behaviour currently, which I will post to the list shortly. After that I will try to spend some time to to a new release candidate and update all of the manuals, website etc. for the new features and parameters for FireHOL/FireQOS.

**Comment by ktsaou** [comment] 2015-01-10 15:55
Phil, I forgot to ask you:

When I was moving all globals to the defaults file, I came accross this `FIREHOL_DEFAULT_NAMESPACE`.

This seems to be interfering with ENABLE_IPV4 and ENABLE_IPV6.

Is it needed any more?

**Comment by philwhineray** [comment] 2015-01-10 16:08
Hi Costa

How exactly do you mean it is interfering exactly? I guess
FIREHOL_DEFAULT_NAMESPACE could be removed by doing a calculation where it
is used, rather than setting it up at the beginning.

It currently takes one of 3 values (depending on ENABLE_IPV4 and
ENABLE_IPV6). It is used to determine whether firehol will work as ipv4,
ipv6 or both whenever a top-level element such as an interface or router is
finished, if the user does not use an explicit value.

**Comment by ktsaou** [comment] 2015-01-10 16:12
In the following code (starting at line 1100), `FIREHOL_DEFAULT_NAMESPACE` may not reflect `ENABLE_IPV4` and `ENABLE_IPv6`.

```sh
if [ $ENABLE_IPV4 -eq 1 -a $ENABLE_IPV6 -eq 1 ]
then
	test -z "$FIREHOL_DEFAULT_NAMESPACE" && \
		FIREHOL_DEFAULT_NAMESPACE=both
elif [ $ENABLE_IPV4 -eq 1 ]
then
	test -z "$FIREHOL_DEFAULT_NAMESPACE" && \
		FIREHOL_DEFAULT_NAMESPACE=ipv4
else
	test -z "$FIREHOL_DEFAULT_NAMESPACE" && \
		FIREHOL_DEFAULT_NAMESPACE=ipv6
fi
```

I understand that your intention was to allow the user set `FIREHOL_DEFAULT_NAMESPACE` as an environment variable.

**Comment by ktsaou** [comment] 2015-01-10 16:14
So, if a user has set `FIREHOL_DEFAULT_NAMESPACE` as an environment variable. `ENABLE_IPV4` and `ENABLE_IPV6` will be incorrectly set.

**Comment by ktsaou** [comment] 2015-01-10 16:16
I understand that we should either remove `ENABLE_IPV*` from defaults or don't allow the user to set `FIREHOL_DEFAULT_NAMESPACE` as an environment variable.

**Comment by philwhineray** [comment] 2015-01-10 16:21
Sorry, yes I did not look close enough.

I believe I had intended that this would allow the user to set e.g. an IPv4
only firewall at a time when ENABLE_IPV4 and ENABLE_IPV6 were not shared
externally.

With them now set in firehol-defaults.conf, I think the  test -z "
$FIREHOL_DEFAULT_NAMESPACE" && is redundant and can be removed and the
variable just set, since the user gets the same control.

**Comment by ktsaou** [comment] 2015-01-10 16:25
ok. I'll do it later today, if you don't have pushed it already.

**Closed by ktsaou** 2015-01-10 16:25 UTC
Labels: enhancement
